# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nobel_prize.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'nobel_prize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11nobel_prize.proto\x12\nnobelprize\"M\n\x13\x43\x61tegoryYearRequest\x12\x10\n\x08\x63\x61tegory\x18\x01 \x01(\t\x12\x12\n\nstart_year\x18\x02 \x01(\x05\x12\x10\n\x08\x65nd_year\x18\x03 \x01(\x05\"+\n\x18MotivationKeywordRequest\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"9\n\x13LaureateNameRequest\x12\x11\n\tfirstname\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\"7\n\x15LaureateCountResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"D\n\x0eLaureateDetail\x12\x0c\n\x04year\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x12\n\nmotivation\x18\x03 \x01(\t\"W\n\x17LaureateDetailsResponse\x12+\n\x07\x64\x65tails\x18\x01 \x03(\x0b\x32\x1a.nobelprize.LaureateDetail\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd1\x02\n\x11NobelPrizeService\x12h\n CountLaureatesByCategoryAndYears\x12\x1f.nobelprize.CategoryYearRequest\x1a!.nobelprize.LaureateCountResponse\"\x00\x12n\n!CountLaureatesByMotivationKeyword\x12$.nobelprize.MotivationKeywordRequest\x1a!.nobelprize.LaureateCountResponse\"\x00\x12\x62\n\x18GetLaureateDetailsByName\x12\x1f.nobelprize.LaureateNameRequest\x1a#.nobelprize.LaureateDetailsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nobel_prize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CATEGORYYEARREQUEST']._serialized_start=33
  _globals['_CATEGORYYEARREQUEST']._serialized_end=110
  _globals['_MOTIVATIONKEYWORDREQUEST']._serialized_start=112
  _globals['_MOTIVATIONKEYWORDREQUEST']._serialized_end=155
  _globals['_LAUREATENAMEREQUEST']._serialized_start=157
  _globals['_LAUREATENAMEREQUEST']._serialized_end=214
  _globals['_LAUREATECOUNTRESPONSE']._serialized_start=216
  _globals['_LAUREATECOUNTRESPONSE']._serialized_end=271
  _globals['_LAUREATEDETAIL']._serialized_start=273
  _globals['_LAUREATEDETAIL']._serialized_end=341
  _globals['_LAUREATEDETAILSRESPONSE']._serialized_start=343
  _globals['_LAUREATEDETAILSRESPONSE']._serialized_end=430
  _globals['_NOBELPRIZESERVICE']._serialized_start=433
  _globals['_NOBELPRIZESERVICE']._serialized_end=770
# @@protoc_insertion_point(module_scope)
