# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import nobel_prize_pb2 as nobel__prize__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in nobel_prize_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NobelPrizeServiceStub(object):
    """Service for querying Nobel Prize data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CountLaureatesByCategoryAndYears = channel.unary_unary(
                '/nobelprize.NobelPrizeService/CountLaureatesByCategoryAndYears',
                request_serializer=nobel__prize__pb2.CategoryYearRequest.SerializeToString,
                response_deserializer=nobel__prize__pb2.LaureateCountResponse.FromString,
                _registered_method=True)
        self.CountLaureatesByMotivationKeyword = channel.unary_unary(
                '/nobelprize.NobelPrizeService/CountLaureatesByMotivationKeyword',
                request_serializer=nobel__prize__pb2.MotivationKeywordRequest.SerializeToString,
                response_deserializer=nobel__prize__pb2.LaureateCountResponse.FromString,
                _registered_method=True)
        self.GetLaureateDetailsByName = channel.unary_unary(
                '/nobelprize.NobelPrizeService/GetLaureateDetailsByName',
                request_serializer=nobel__prize__pb2.LaureateNameRequest.SerializeToString,
                response_deserializer=nobel__prize__pb2.LaureateDetailsResponse.FromString,
                _registered_method=True)


class NobelPrizeServiceServicer(object):
    """Service for querying Nobel Prize data
    """

    def CountLaureatesByCategoryAndYears(self, request, context):
        """Service 1: Count laureates by category and year range
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountLaureatesByMotivationKeyword(self, request, context):
        """Service 2: Count laureates by motivation keyword
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLaureateDetailsByName(self, request, context):
        """Service 3: Get laureate details by name
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NobelPrizeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CountLaureatesByCategoryAndYears': grpc.unary_unary_rpc_method_handler(
                    servicer.CountLaureatesByCategoryAndYears,
                    request_deserializer=nobel__prize__pb2.CategoryYearRequest.FromString,
                    response_serializer=nobel__prize__pb2.LaureateCountResponse.SerializeToString,
            ),
            'CountLaureatesByMotivationKeyword': grpc.unary_unary_rpc_method_handler(
                    servicer.CountLaureatesByMotivationKeyword,
                    request_deserializer=nobel__prize__pb2.MotivationKeywordRequest.FromString,
                    response_serializer=nobel__prize__pb2.LaureateCountResponse.SerializeToString,
            ),
            'GetLaureateDetailsByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLaureateDetailsByName,
                    request_deserializer=nobel__prize__pb2.LaureateNameRequest.FromString,
                    response_serializer=nobel__prize__pb2.LaureateDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nobelprize.NobelPrizeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nobelprize.NobelPrizeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NobelPrizeService(object):
    """Service for querying Nobel Prize data
    """

    @staticmethod
    def CountLaureatesByCategoryAndYears(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobelprize.NobelPrizeService/CountLaureatesByCategoryAndYears',
            nobel__prize__pb2.CategoryYearRequest.SerializeToString,
            nobel__prize__pb2.LaureateCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountLaureatesByMotivationKeyword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobelprize.NobelPrizeService/CountLaureatesByMotivationKeyword',
            nobel__prize__pb2.MotivationKeywordRequest.SerializeToString,
            nobel__prize__pb2.LaureateCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLaureateDetailsByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nobelprize.NobelPrizeService/GetLaureateDetailsByName',
            nobel__prize__pb2.LaureateNameRequest.SerializeToString,
            nobel__prize__pb2.LaureateDetailsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
