version: '3.8'
services:
  nobel-grpc-service:
    build: .
    ports:
      - "50051:50051"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
